apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapacity-collector-deployment
  namespace: kapacity
  labels:
    app: kapacity-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kapacity-collector
  template:
    metadata:
      labels:
        app: kapacity-collector
    spec:
      serviceAccountName: kapacity-collector-sa  # Specify the ServiceAccount here
      containers:
      - name: kapacity-collector
        image: ghcr.io/aetrius/kube-resource-viewer:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
