apiVersion: v1
kind: Service
metadata:
  name: kapacity-collector-service
  namespace: kapacity
  labels:
    app: kapacity-collector
spec:
  type: ClusterIP  # Use NodePort or LoadBalancer if external access is required
  selector:
    app: kapacity-collector
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
