apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-resource-viewer-deployment
  namespace: kube-resource-viewer
  labels:
    app: kube-resource-viewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-resource-viewer
  template:
    metadata:
      labels:
        app: kube-resource-viewer
    spec:
      serviceAccountName: kube-resource-viewer-sa  # Specify the ServiceAccount here
      containers:
      - name: kube-resource-viewer
        image: ghcr.io/aetrius/kube-resource-viewer/kube-resource-viewer:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
