
CREATE USER k8s_user WITH PASSWORD 'USER_PASSWORD_GOES_HERE';
GRANT ALL privileges ON DATABASE rootly to k8s_user;
GRANT ALL ON DATABASE rootly TO k8s_user WITH GRANT OPTION;
GRANT ALL ON SCHEMA public TO k8s_user WITH GRANT OPTION;
--