apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kapacity
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: kapacity-db
        - name: POSTGRES_USER
          value: kapacity-admin
        - name: POSTGRES_PASSWORD
          value: K@Passity!
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim